export const DISCLAIMER_SECTIONS = [
  {
    title: "Disclaimer",
    body: 'This financial planning software and all associated financial calculators (collectively, the "Software") are provided strictly for informational and educational purposes only. They do not constitute financial, investment, tax, legal, accounting, or any other form of professional advice.',
  },
  {
    title: "No Professional Advice",
    body: "The outputs, calculations, projections, recommendations, or any other information generated by the Software are general in nature and are not tailored to your individual financial situation, goals, risk tolerance, or needs. You acknowledge and agree that you are solely responsible for determining whether any information provided is appropriate for your circumstances.",
  },
  {
    title: "No Guarantees or Warranties",
    body: "We make no representations or warranties of any kind, express or implied, regarding the accuracy, completeness, reliability, timeliness, suitability, or availability of the Software or any content generated by it. All calculations, forecasts, and results are based on assumptions, historical data, and mathematical models that may not reflect future performance or your specific facts. Past performance is not indicative of future results. Market conditions, tax laws, regulations, and personal circumstances change constantly.",
  },
  {
    title: "User Assumes All Risk",
    body: "You assume full and complete responsibility and risk for any and all use of the Software. Any decisions you make based on the Software are made entirely at your own risk. We are not liable for any errors, omissions, inaccuracies, or inconsistencies in the Software or its outputs.",
  },
  {
    title: "Limitation of Liability",
    body: "To the maximum extent permitted by law, the creators, developers, owners, operators, affiliates, and licensors of the Software shall not be liable for any direct, indirect, incidental, special, consequential, punitive, or exemplary damages (including but not limited to loss of profits, savings, data, goodwill, or any financial or investment losses) arising out of or in connection with the use of, or inability to use, the Software - even if advised of the possibility of such damages.",
  },
  {
    title: "Consult Qualified Professionals",
    body: "You should always consult with a qualified, licensed financial advisor, accountant, tax professional, attorney, or other appropriate expert before making any financial, investment, retirement, estate planning, or tax-related decisions. Do not rely on this Software as a substitute for professional advice.",
  },
  {
    title: "No Endorsement",
    body: "Any references to third-party products, services, or websites are for convenience only and do not constitute an endorsement or recommendation.",
  },
] as const;

export const DISCLAIMER_CLOSING = [
  "Securities and investment advisory services offered through Osaic Wealth, Inc. member FINRA/SIPC. Osaic Wealth is separately owned and other entities and/or marketing names, products or services referenced here are independent of Osaic Wealth.",
  "By accessing or using the Software, you expressly acknowledge that you have read, understood, and agreed to this Disclaimer in its entirety. If you do not agree with any part of this Disclaimer, you must immediately cease using the Software.",
  "This Disclaimer is subject to change without notice. It is your responsibility to review it periodically.",
] as const;
