export const TERMS_VERSION = "2026-09-27b";
export const TERMS_EFFECTIVE_DATE = "September 27, 2026";

export const TERMS_SECTIONS = [
  {
    title: "Agreement to these Terms",
    body: 'These Terms of Use (the "Terms") constitute a legally binding agreement between you ("you," "your," or "User") and Wisdom and a Moment ("Wisdom and a Moment," "we," "us," or "our"), the company that operates Roth RR. These Terms govern your access to and use of Roth RR websites, applications, calculators, tools, content, communications, and related services (collectively, the "Software"). By accessing, browsing, registering for, or otherwise using the Software in any way, you acknowledge that you have read, understood, and agree to be bound by these Terms, our Privacy Policy, and our Disclaimer, each of which is incorporated herein by reference. If you do not agree to every provision of these Terms, you must immediately cease all use of the Software.',
  },
  {
    title: "Eligibility and authority",
    body: "You represent and warrant that you are at least eighteen (18) years of age (or the age of majority in your jurisdiction, if older) and have the legal capacity to enter into a binding contract. If you access or use the Software on behalf of an entity, you represent and warrant that you have full legal authority to bind that entity to these Terms, and \"you\" includes that entity. The Software is intended for users located in jurisdictions where its use is lawful. You are solely responsible for compliance with all laws applicable to your use.",
  },
  {
    title: "Informational and educational use only",
    body: 'The Software is provided strictly "as is" and solely for general informational and educational purposes. The Software is not, and is not intended or represented to be: (a) professional financial planning software; (b) a substitute for professional-grade advisory, tax, accounting, or legal software or tools; (c) personalized financial, investment, tax, legal, accounting, retirement, estate, insurance, or any other professional advice; or (d) an offer, solicitation, recommendation, or endorsement to buy, sell, hold, convert, or otherwise transact in any security, account, product, or strategy. All outputs, calculations, projections, estimates, comparisons, schedules, illustrations, scenarios, ranges, and other results generated by the Software (collectively, "Outputs") are hypothetical, model-based, and general in nature. Outputs are not tailored to your individual facts, objectives, risk tolerance, tax situation, or legal needs.',
  },
  {
    title: "No professional or fiduciary relationship",
    body: "Your access to or use of the Software does not create any fiduciary, advisory, broker-dealer, investment-adviser, attorney-client, accountant-client, tax-preparer, or other professional relationship between you and Wisdom and a Moment, Roth RR, or any of their owners, creators, operators, employees, contractors, affiliates, or licensors (collectively, the \"Roth RR Parties\"). Neither Wisdom and a Moment nor Roth RR is a registered investment adviser, broker-dealer, bank, trust company, insurance agency, CPA firm, tax preparation firm, or law firm. Nothing in the Software should be construed as creating such a relationship or as a commitment to provide ongoing advice or monitoring.",
  },
  {
    title: "No reliance; user assumes all risk",
    body: "You expressly acknowledge and agree that: (a) you will not rely on the Software or any Outputs as the sole or primary basis for any financial, investment, tax, retirement, estate, legal, or other decision; (b) you assume full and exclusive responsibility and risk for all use of the Software and for all decisions, actions, and omissions made in connection with or based on the Software or Outputs; (c) any reliance you place on the Software or Outputs is entirely at your own risk; and (d) before making any such decision, you should consult one or more qualified, licensed professionals (including, as applicable, a financial advisor, tax professional, CPA, attorney, or other expert) who can evaluate your complete facts and applicable law. Roth RR Parties have no duty to update Outputs, verify your inputs, or warn you of errors, omissions, law changes, or market changes.",
  },
  {
    title: "Nature of calculations and models",
    body: "Outputs are based on user-provided inputs, assumptions, estimates, simplified models, mathematical approximations, historical or reference data, and/or third-party information that may be incomplete, outdated, incorrect, or inapplicable to you. Tax brackets, RMD rules, Medicare/IRMAA thresholds, growth rates, inflation, mortality, Social Security, state taxes, and other parameters may change, may be modeled incompletely, or may not reflect your jurisdiction or personal facts. Past performance is not indicative of future results. Markets, tax laws, regulations, and personal circumstances change constantly. Roth RR Parties do not warrant that any Output is accurate, complete, current, suitable, or free from error, and expressly disclaim any obligation to correct defects or to achieve any particular financial or tax outcome.",
  },
  {
    title: "Fees and future pricing",
    body: "The Software is currently offered free of charge. You acknowledge and agree that Wisdom and a Moment reserves the absolute right, at any time and in its sole discretion, with or without prior notice to the maximum extent permitted by law, to: (a) introduce fees for the Software or for any feature, plan, tier, calculator, storage, support, or related service, including features that are free today; (b) change prices, billing models, or packaging; (c) require payment as a condition of continued access to some or all features; and (d) discontinue free access entirely or in part. We may provide notice of material pricing changes via the Software, email, or an update to these Terms. Continued use of a paid feature after fees apply constitutes acceptance of those fees. Nothing in these Terms obligates us to keep any feature free, to offer refunds (except where required by law), or to maintain any pricing for any period.",
  },
  {
    title: "Accounts, credentials, and user data",
    body: "If you create an account or otherwise submit information, you agree to provide true, accurate, and complete information and to keep it updated. You are solely responsible for safeguarding credentials, magic links, devices, and access methods, and for all activity occurring under your account or from your devices, whether or not authorized by you. You must notify us promptly at support@thewealthlab.com if you suspect unauthorized access. We may refuse registration, or suspend, restrict, or terminate accounts, at any time, with or without notice, for any reason or no reason, including suspected misuse, security risk, inactivity, or violation of these Terms. You are solely responsible for exporting or backing up any plans or data you wish to retain. We have no liability for loss of plans, inputs, Outputs, or other data.",
    link: {
      href: "mailto:support@thewealthlab.com",
      label: "support@thewealthlab.com",
    },
  },
  {
    title: "Acceptable use",
    body: "You agree not to, and not to attempt to: (a) use the Software for any unlawful, fraudulent, deceptive, or harmful purpose; (b) violate any applicable law or third-party right; (c) gain unauthorized access to the Software, accounts, systems, networks, or data; (d) interfere with, disrupt, overload, or impair the Software or related infrastructure; (e) reverse engineer, decompile, disassemble, or otherwise attempt to derive source code or underlying models except to the limited extent such restriction is prohibited by law; (f) copy, scrape, harvest, crawl, mine, frame, mirror, or systematically extract content, data, or Outputs except as expressly permitted; (g) circumvent authentication, rate limits, paywalls, or security controls; (h) introduce malware, bots, or automated means that impair the Software; (i) misrepresent your identity or affiliation; (j) use Outputs or the Software to provide regulated advice to third parties without required licenses; or (k) otherwise use the Software in any manner that could damage, disable, or impair Roth RR or other users.",
  },
  {
    title: "Intellectual property",
    body: "The Software, including all software, code, models, algorithms, designs, text, graphics, logos, trademarks, trade dress, audiovisual elements, documentation, and other content (excluding User Content, as defined below), is and remains the exclusive property of Wisdom and a Moment or its licensors and is protected by copyright, trademark, trade secret, and other intellectual property laws. Subject to these Terms, we grant you a limited, revocable, non-exclusive, non-transferable, non-sublicensable license to access and use the Software solely for your personal, non-commercial informational and educational purposes (or internal educational use if you are an entity), and solely in accordance with these Terms. No other rights are granted by implication or otherwise. You may not copy, modify, distribute, publicly display, sell, lease, sublicense, or create derivative works from the Software without our prior written consent.",
  },
  {
    title: "User Content and feedback",
    body: '\"User Content\" means any plans, inputs, data, text, feedback, ideas, suggestions, or other materials you submit to or through the Software. You retain whatever ownership rights you have in User Content. You grant Wisdom and a Moment a worldwide, perpetual, irrevocable, royalty-free, fully paid, transferable, and sublicensable license to use, host, store, reproduce, modify, adapt, publish, translate, create derivative works from, distribute, and otherwise process User Content as reasonably necessary to operate, secure, analyze, and improve the Software and to communicate with you. Feedback and ideas may be used by Wisdom and a Moment without restriction, attribution, or compensation. You represent that you have all rights necessary to submit User Content and that it does not violate law or third-party rights.',
  },
  {
    title: "Third-party services and links",
    body: "The Software may integrate with, depend on, or link to third-party websites, tools, platforms, and service providers, including without limitation hosting, authentication, email delivery, analytics (such as Google Analytics and Microsoft Clarity), mailing-list providers (such as Mailchimp), and advertising or retargeting partners (such as Google, Meta, and TikTok). Those third parties are independent of Wisdom and a Moment and Roth RR. Your dealings with third parties are solely between you and them and may be governed by their own terms and privacy policies. Any references to third-party products, services, websites, tools, or content are for convenience only and do not constitute an endorsement, recommendation, sponsorship, or affiliation. ROTH RR PARTIES MAKE NO REPRESENTATIONS OR WARRANTIES REGARDING THIRD-PARTY SERVICES AND DISCLAIM ALL LIABILITY ARISING FROM OR RELATED TO THIRD-PARTY SERVICES, CONTENT, ACTS, OMISSIONS, OUTAGES, DATA PRACTICES, SECURITY INCIDENTS, OR FAILURES, WHETHER OR NOT WE INTEGRATE OR REFER TO THEM.",
  },
  {
    title: "Disclaimer of warranties",
    body: 'TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE SOFTWARE, OUTPUTS, AND ALL RELATED CONTENT AND SERVICES ARE PROVIDED "AS IS," "AS AVAILABLE," AND "WITH ALL FAULTS," WITHOUT WARRANTY OF ANY KIND. ROTH RR PARTIES EXPRESSLY DISCLAIM ALL WARRANTIES, WHETHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, INCLUDING BUT NOT LIMITED TO IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, NON-INFRINGEMENT, ACCURACY, COMPLETENESS, RELIABILITY, TIMELINESS, SECURITY, QUIET ENJOYMENT, AND ANY WARRANTIES ARISING FROM COURSE OF DEALING OR USAGE OF TRADE. WITHOUT LIMITING THE FOREGOING, ROTH RR PARTIES DO NOT WARRANT THAT: (A) THE SOFTWARE OR OUTPUTS WILL MEET YOUR REQUIREMENTS OR EXPECTATIONS; (B) THE SOFTWARE WILL BE UNINTERRUPTED, TIMELY, SECURE, VIRUS-FREE, OR ERROR-FREE; (C) DEFECTS WILL BE CORRECTED; (D) ANY CALCULATION, PROJECTION, TAX ESTIMATE, MEDICARE ESTIMATE, RMD FIGURE, OR OTHER OUTPUT IS CORRECT OR SUITABLE FOR ANY PURPOSE; OR (E) ANY PARTICULAR FINANCIAL, TAX, OR OTHER RESULT WILL BE ACHIEVED. SOME JURISDICTIONS DO NOT ALLOW CERTAIN DISCLAIMERS; IN SUCH CASES, THE DISCLAIMERS APPLY TO THE FULLEST EXTENT PERMITTED.',
  },
  {
    title: "Limitation of liability",
    body: "TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT SHALL ROTH RR PARTIES BE LIABLE TO YOU OR ANY THIRD PARTY FOR ANY INDIRECT, INCIDENTAL, SPECIAL, CONSEQUENTIAL, PUNITIVE, EXEMPLARY, OR ENHANCED DAMAGES; OR FOR ANY LOSS OF PROFITS, REVENUE, INCOME, SAVINGS, BUSINESS, GOODWILL, DATA, USE, OR OTHER INTANGIBLE LOSSES; OR FOR ANY FINANCIAL, INVESTMENT, TAX, RETIREMENT, ESTATE, OR OTHER ECONOMIC LOSSES OR OPPORTUNITY COSTS; ARISING OUT OF OR RELATED TO THESE TERMS, THE SOFTWARE, OUTPUTS, OR YOUR USE OF OR INABILITY TO USE THE SOFTWARE, REGARDLESS OF THEORY OF LIABILITY (CONTRACT, TORT INCLUDING NEGLIGENCE, STRICT LIABILITY, WARRANTY, STATUTE, OR OTHERWISE), AND EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGES OR IF A REMEDY FAILS OF ITS ESSENTIAL PURPOSE. TO THE MAXIMUM EXTENT PERMITTED BY LAW, ROTH RR PARTIES' TOTAL AGGREGATE LIABILITY FOR ALL CLAIMS ARISING OUT OF OR RELATING TO THESE TERMS, THE SOFTWARE, OR OUTPUTS SHALL NOT EXCEED THE GREATER OF: (A) THE TOTAL AMOUNTS (IF ANY) YOU PAID TO WISDOM AND A MOMENT FOR THE SOFTWARE IN THE TWELVE (12) MONTHS IMMEDIATELY PRECEDING THE EVENT GIVING RISE TO THE CLAIM; OR (B) ONE HUNDRED U.S. DOLLARS (US $100). THE FOREGOING LIMITATIONS ARE AN ESSENTIAL BASIS OF THE BARGAIN AND APPLY EVEN IF THE SOFTWARE IS PROVIDED FREE OF CHARGE.",
  },
  {
    title: "Release",
    body: "To the maximum extent permitted by law, you hereby release and forever discharge the Roth RR Parties from any and all claims, demands, causes of action, damages, losses, and liabilities of every kind and nature, known or unknown, suspected or unsuspected, arising out of or related to your use of the Software, reliance on Outputs, decisions made in connection with the Software, third-party services, or any dispute with another user or third party. If you are a California resident, you waive California Civil Code Section 1542 (and any similar law), which provides that a general release does not extend to claims that the releasing party does not know or suspect to exist at the time of executing the release and that, if known, would have materially affected the settlement.",
  },
  {
    title: "Indemnification",
    body: "You agree to defend, indemnify, and hold harmless the Roth RR Parties from and against any and all claims, demands, actions, proceedings, losses, liabilities, damages, judgments, settlements, costs, and expenses (including reasonable attorneys' fees and costs) arising out of or related to: (a) your access to or use of the Software; (b) your User Content; (c) your reliance on Outputs or any decision made in connection with the Software; (d) your violation of these Terms, the Privacy Policy, the Disclaimer, or any law; (e) your violation of any third-party right; or (f) any dispute between you and a third party. We may assume exclusive defense and control of any matter subject to indemnification; you agree to cooperate and not settle any such matter without our prior written consent.",
  },
  {
    title: "Suspension, termination, and discontinuation",
    body: "We may, at any time and for any reason or no reason, with or without notice, suspend, restrict, modify, or terminate your access to the Software (in whole or in part), or discontinue the Software entirely. You may stop using the Software at any time. Upon termination or discontinuation, your license ends immediately. We shall have no liability to you for any suspension, termination, modification, or discontinuation. Provisions that by their nature should survive (including ownership, licenses to User Content and feedback, disclaimers, limitations of liability, release, indemnification, governing law, and dispute terms) shall survive.",
  },
  {
    title: "Changes to the Software or Terms",
    body: "We reserve the right to modify, update, or replace these Terms at any time. The effective date will be revised when changes are posted. Except where prohibited by law, changes are effective upon posting. Your continued use of the Software after changes become effective constitutes acceptance. If you do not agree, you must stop using the Software. We may also change, add, or remove features of the Software at any time without liability.",
  },
  {
    title: "Force majeure",
    body: "Roth RR Parties shall not be liable for any failure or delay in performance resulting from causes beyond their reasonable control, including acts of God, natural disasters, war, terrorism, riots, embargoes, acts of civil or military authorities, fire, floods, accidents, strikes, shortages, network or telecommunications failures, cyberattacks, power outages, or failures of third-party providers.",
  },
  {
    title: "Governing law and venue",
    body: "These Terms and any dispute arising out of or relating to these Terms, the Software, or Outputs shall be governed by and construed in accordance with the laws of the State of Florida, United States, without regard to conflict-of-law principles. Except where prohibited by law, you agree that the exclusive venue for any judicial proceeding shall be the state or federal courts located in the State of Florida, and you consent to personal jurisdiction and venue in those courts. YOU AND WISDOM AND A MOMENT WAIVE ANY RIGHT TO A JURY TRIAL TO THE MAXIMUM EXTENT PERMITTED BY LAW. Some jurisdictions do not allow certain limitations; those limitations apply to the fullest extent permitted.",
  },
  {
    title: "Dispute resolution and class-action waiver",
    body: "To the maximum extent permitted by law, you agree that any dispute, claim, or controversy arising out of or relating to these Terms or the Software will be brought only in your individual capacity, and not as a plaintiff or class member in any purported class, collective, consolidated, or representative proceeding. You waive any right to participate in a class action or class-wide arbitration against the Roth RR Parties. If a court of competent jurisdiction finds this waiver unenforceable as to a particular claim, then that claim (and only that claim) may proceed in court on an individual basis, and all other claims remain subject to these Terms.",
  },
  {
    title: "Export and sanctions compliance",
    body: "You may not use, export, or re-export the Software except as authorized by United States law and the laws of the jurisdiction in which the Software was obtained. You represent that you are not located in, under the control of, or a national or resident of any country or person subject to U.S. embargoes or sanctions, and that you are not on any U.S. government list of prohibited or restricted parties.",
  },
  {
    title: "Miscellaneous",
    body: "These Terms, together with the Privacy Policy, Disclaimer, and any other policies we expressly incorporate, constitute the entire agreement between you and Wisdom and a Moment regarding the Software and supersede all prior or contemporaneous understandings. If any provision is held invalid or unenforceable, it will be modified to the minimum extent necessary to make it enforceable, or if modification is not possible, severed, and the remaining provisions will continue in full force. Our failure to enforce any provision is not a waiver of that provision or any other. You may not assign or transfer these Terms without our prior written consent; any attempted assignment in violation of this clause is void. We may assign these Terms without restriction, including in connection with a merger, acquisition, corporate reorganization, or sale of assets. Headings are for convenience only and do not affect interpretation. The English language version controls. Nothing in these Terms creates any third-party beneficiary rights except for the Roth RR Parties with respect to disclaimers, limitations, release, and indemnification.",
  },
  {
    title: "Contact",
    body: "Questions about these Terms may be sent to support@thewealthlab.com.",
    link: {
      href: "mailto:support@thewealthlab.com",
      label: "support@thewealthlab.com",
    },
  },
] as const;
